package com.ponominalu.nvv.ponominalutest.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

    private Long id;
    private String title;
    private String alias;
    private Long events_count;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String title, String alias, Long events_count) {
        this.id = id;
        this.title = title;
        this.alias = alias;
        this.events_count = events_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Long getEvents_count() {
        return events_count;
    }

    public void setEvents_count(Long events_count) {
        this.events_count = events_count;
    }

}
