package com.ponominalu.nvv.ponominalutest.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ponominalu.nvv.ponominalutest.dao.Category;
import com.ponominalu.nvv.ponominalutest.dao.Event;

import com.ponominalu.nvv.ponominalutest.dao.CategoryDao;
import com.ponominalu.nvv.ponominalutest.dao.EventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig eventDaoConfig;

    private final CategoryDao categoryDao;
    private final EventDao eventDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Event.class, eventDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

}
