package com.ponominalu.nvv.ponominalutest.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.ArrayList;
import java.util.List;

/**
 * Entity mapped to table EVENT.
 */
public class Event {

    private Long id;
    private String title;
    private List<Subevent> subevents;
    private String description;
    private Long category_id;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String title, Long sub_id, String date, String end_date, String image_name, byte[] image, Long min_price, Long max_price, Long count, String description, Long category_id) {
        this.id = id;
        this.title = title;
        this.getSubevents().get(0).id = sub_id;
        this.getSubevents().get(0).date = date;
        this.getSubevents().get(0).end_date = end_date;
        this.getSubevents().get(0).image = image_name;
        this.getSubevents().get(0).image_bytes = image;
        this.getSubevents().get(0).min_price = min_price;
        this.getSubevents().get(0).max_price = max_price;
        this.getSubevents().get(0).count = count;
        this.description = description;
        this.category_id = category_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<Subevent> getSubevents() {
        if (subevents==null){
            subevents = new ArrayList<>();
            subevents.add(new Subevent());
        }
        return subevents;
    }

    public void setSubevents(List<Subevent> subevents) {
        this.subevents = subevents;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public class Subevent{
        private Long id;
        private String date;
        private String end_date;
        private String image;
        private byte[] image_bytes;
        private Long min_price;
        private Long max_price;
        private Long count;


        public Long getSub_id() {
            return id;
        }

        public void setSub_id(Long sub_id) {
            this.id = sub_id;
        }

        public String getDate() {
            return date;
        }

        public void setDate(String date) {
            this.date = date;
        }

        public String getEnd_date() {
            return end_date;
        }

        public void setEnd_date(String end_date) {
            this.end_date = end_date;
        }

        public String getImage_name() {
            return image;
        }

        public void setImage_name(String image) {
            this.image = image;
        }

        public byte[] getImage() {
            return image_bytes;
        }

        public void setImage(byte[] image_bytes) {
            this.image_bytes = image_bytes;
        }

        public Long getMin_price() {
            return min_price;
        }

        public void setMin_price(Long min_price) {
            this.min_price = min_price;
        }

        public Long getMax_price() {
            return max_price;
        }

        public void setMax_price(Long max_price) {
            this.max_price = max_price;
        }

        public Long getCount() {
            return count;
        }

        public void setCount(Long count) {
            this.count = count;
        }
    }

}
